field: a3cbc9e5-90e6-4e9c-a53a-4663268e0ba3
fieldLayouts:
  ff73a5e9-4b75-4e36-a669-089c2336f5be:
    tabs:
      -
        elements:
          -
            fieldUid: b58081ce-ecc0-4ee6-a495-eb061fb4d6e2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: beb33420-3a82-4712-b26c-335e315f00a7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b58081ce-ecc0-4ee6-a495-eb061fb4d6e2:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:8561db5e-5e44-4a78-b8b0-6979fffa5315'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8561db5e-5e44-4a78-b8b0-6979fffa5315'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  beb33420-3a82-4712-b26c-335e315f00a7:
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: ''
    name: 'Image Caption'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeImage
name: 'Recipe Image'
sortOrder: 1
