field: a3cbc9e5-90e6-4e9c-a53a-4663268e0ba3
fieldLayouts:
  e5ae5cfd-83b7-4b52-b0ae-b4ccec1c862b:
    tabs:
      -
        elements:
          -
            fieldUid: 2d6fda19-88c3-4267-aa80-2fc831de19c8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2d6fda19-88c3-4267-aa80-2fc831de19c8:
    contentColumnType: text
    fieldGroup: null
    handle: ingredients
    instructions: ''
    name: Ingredients
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Amount
                -
                  - handle
                  - amount
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Ingredient
                -
                  - handle
                  - ingredient
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: recipeIngredients
name: 'Recipe Ingredients'
sortOrder: 5
