enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  a396edee-fb18-4ab0-99f2-9d7727c01555:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
