enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  a396edee-fb18-4ab0-99f2-9d7727c01555:
    enabledByDefault: true
    hasUrls: true
    template: news\_entry
    uriFormat: 'news/{slug}'
type: channel
