enableVersioning: true
handle: recipes
name: Recipes
propagationMethod: all
siteSettings:
  a396edee-fb18-4ab0-99f2-9d7727c01555:
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry
    uriFormat: 'recipes/{slug}'
type: channel
